# Generated by Django 4.1.7 on 2023-03-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioexam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name': 'Аудио', 'verbose_name_plural': 'Аудио'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='audioexam\\audio_files\\', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
