# Generated by Django 4.1.7 on 2023-03-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioexam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='.\\audio_files\\', verbose_name='Аудио'),
        ),
    ]
