# Generated by Django 4.1.7 on 2023-03-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioexam', '0002_alter_audio_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='audio_files\\', verbose_name='Аудио'),
        ),
    ]
