# Generated by Django 4.1.7 on 2023-03-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioexam', '0003_alter_audio_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='', verbose_name='Аудио'),
        ),
    ]
